{
 "title": "MyK8S",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "container_cpu_usage_seconds_total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sort_desc(rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[5m])))",
     "legendFormat": "{{pod}}:{{container}}"
    }
   ]
  },
  {
   "title": "MemoryRSS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,sort_desc(avg_over_time(container_memory_rss{container!=\"POD\",container!=\"\"}[3m])))",
     "legendFormat": "{{pod}}:{{container}}"
    }
   ]
  },
  {
   "title": "IOReads",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sort_desc(sum(rate(container_fs_writes_bytes_total{container!=\"\"}[1m])) by (pod,container,device)>0))",
     "legendFormat": "{{pod}}:{{container}}:{{device}}"
    }
   ]
  },
  {
   "title": "IOWrites",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sort_desc(sum(rate(container_fs_writes_bytes_total{container!=\"\"}[1m])) by (pod,container,device)>0))",
     "legendFormat": "{{pod}}:{{container}}:{{device}}"
    }
   ]
  },
  {
   "title": "Pods Network Recieve",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sort_desc(sum(rate(container_network_receive_bytes_total{pod!=\"\"}[5m])) by (instance,pod)))"
    }
   ]
  },
  {
   "title": "container_network_transmit_bytes_total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sort_desc(sum(rate(container_network_transmit_bytes_total{pod!=\"\"}[5m])) by (instance,pod)))"
    }
   ]
  },
  {
   "title": "MemberUpAlive",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up",
     "legendFormat": "{{instance}}:{{job}}:{{k8s_app}}"
    }
   ]
  },
  {
   "title": "pod not running",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{phase!=\"Running\"}) by (pod,phase)"
    }
   ]
  },
  {
   "title": "ContainerFDS",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sort_desc(avg_over_time(container_file_descriptors{container!=\"POD\",container!=\"\"}[5m])))",
     "legendFormat": "{{pod}}:{{container}}"
    }
   ]
  },
  {
   "title": "kubelet_http_requests_total",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kubelet_http_requests_total) by(instance,method)",
     "legendFormat": "{{instance}}:{{method}}"
    }
   ]
  },
  {
   "title": "kube_pod_container_status_restarts_total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase (kube_pod_container_status_restarts_total{}[2m])) by (namespace,pod)"
    }
   ]
  }
 ]
}