#!/bin/bash
# Switch docker containers as select menu
# Auther: schat 
#
# Usage: chmod +x /data/docker/dockerin; ln -s /data/docker/dockerin /usr/local/bin/
# $ dockerin
#   1) gitlab(172.17.0.3)
#   2) test(172.17.0.2)
#   #? 2
#

if [ $# -eq 1 -a "$1" = "-h" ]
then	
   echo 'net=" --net=dockernet "'
   echo 'sysopts=" --privileged=true --cap-add=SYS_ADMIN -v /run -v /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro --security-opt seccomp=unconfined "'
   echo -e 'name=gantt; ip=172.17.0.18; data=/data/docker/disks/$name/data; docker run $sysopts -it -d -h $name --name $name --ip=$ip $net -v "$data:/data" -w /data -h $name --name $name --restart=always harbor.a.com:9443/myimgs/myubuntu:20.04 /usr/sbin/init\n'
fi

if [ ! -f /usr/local/bin/dockergetip ]
then
   cat > /usr/local/bin/dockergetip <<'_EOF_'
#!/bin/bash
function getip(){
   name=${1/:/}
   docker inspect $name|grep '"IPAddress": "[0-9]\+.*"'|head -n1|awk '{print $2}'|sed -e 's/"//g' -e 's/,//g'|xargs -I {} echo "$name({})"
}
getip $1
_EOF_

   sudo chmod +x /usr/local/bin/dockergetip
fi

select c  in $( sudo docker ps |awk 'NR>1 {print $NF}'|xargs -I {} sudo /usr/local/bin/dockergetip {})
do
  name=$(echo $c|sed -e 's/(.*)//g' -e 's/://g')
  sudo docker exec -it $name bash
done
